#!/bin/bash

function Usage {
    myname=$0
    myname=${myname##*/}
    cat << EOF
${myname} runs skullstripping on MP2RAGE images with the uniform tissue contrast image (uni_fname)  and the 2nd inversion image (inv2_fname) by

[1] multiplying uni and inv2 (*)
[2] and using skull-stripping using VBM8/SPM

and returns skull-stripped image (uni_fname+"_mp2brain.nii" by default)

Usage  : ${myname} [uni_filename] [inv2_filename] ([output_filename])
(arguments)
  [uni-filename]  : filename of uniform contrast image from MP2RAGE sequence
  [inv2-filename] : filename of the second inversion image from MP2RAGE sequence
  [output]        : (optional) output filename

* Ref: Fujimoto et al, 2014, NeuroImage. 

Example: ${myname} mp2rage_uni.nii mp2rage_inv2.nii

NOTE: You need to have SPM executable and "vbm8_brainExt_exit.m" in your MATLAB working path.

(cc) 2014, 2015, sgKIM. solleo@gmail.com

EOF
}

#set -x
# 0. parse input arguments
if [ $# -lt 1 ]; then
    Usage
    exit 1
fi
uni=$1
inv2=$2

# 1. gunzip
uni=`mynifti $1`
inv2=`mynifti $2`
mkdir .temp$$
cp $uni ./.temp$$/`imglob $uni`.nii
cp $inv2 .temp$$/`imglob $inv2`.nii
cd ./.temp$$

if [ ! $3 ]; then
    output=`imglob $uni`_mp2brain.nii
else
    output=$3
fi

# 1. Mutiply them in store in float precision (Fujimoto et al., 2014, NI)
FSLOUTPUTTYPE=NIFTI
fslmaths ${uni} -mul ${inv2} mp2.nii -odt float

# 2. Feed the multiplication into VBM8
satlab8 -nodesktop -nosplash -r "vbm8_brainExt_exit({'mp2.nii'});"

# 3. Apply the brain mask to the unbiased uniform image:
fslmaths p1mp2 -add p2mp2 -add p3mp2 -bin -mul $uni ${output}

# 5. return results and remove the temporary directory
cp ${output} ../
cp mp2.nii ../`imglob $uni`_UNIxINV2.nii
cd ..
rm -rf ./.temp$$


